//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.tareas = new HashSet<tarea>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string puesto { get; set; }
    
        public virtual ICollection<tarea> tareas { get; set; }
    }
}
